// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://google.com",
        "contact": {
            "name": "Tardelli Moura",
            "url": "https://google.com",
            "email": "tardelli.m@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calc": {
            "post": {
                "description": "Calcule Capital Gain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calc"
                ],
                "summary": "Calcule Capital Gain",
                "parameters": [
                    {
                        "description": "Operations JSON",
                        "name": "operations",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Oper"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.FeeResponse"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Responds running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthZ"
                ],
                "summary": "healthz",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.FeeResponse": {
            "type": "object",
            "properties": {
                "tax": {
                    "type": "number"
                }
            }
        },
        "domain.Oper": {
            "type": "object",
            "properties": {
                "operation": {
                    "$ref": "#/definitions/domain.OperationType"
                },
                "quantity": {
                    "type": "integer"
                },
                "unit-cost": {
                    "type": "number"
                }
            }
        },
        "domain.OperationType": {
            "type": "string",
            "enum": [
                "buy",
                "sell"
            ],
            "x-enum-varnames": [
                "Buy",
                "Sell"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Desafio Nu",
	Description:      "Desafio de calculo de ganho de capital.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
